# Generated by Django 3.0.3 on 2020-03-01 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catmat', models.CharField(max_length=6, unique=True)),
                ('category', models.CharField(choices=[('REAGENTE', 'Reagentes'), ('EPI', 'EPI'), ('CORRELATO', 'Correlatos'), ('MEIO DE CULTURA', 'Meios de Cultura'), ('ANTIBIOGRAMA', 'Antibiograma')], max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('presentation', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
