# Generated by Django 3.0.3 on 2020-03-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Reagentes', 'Reagentes'), ('EPIs', 'EPIs'), ('Correlatos', 'Correlatos'), ('Meios de Cultura', 'Meios de Cultura'), ('Antibiograma', 'Antibiograma')], max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('presentation', models.CharField(max_length=40)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
