# Generated by Django 3.0.3 on 2020-04-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PgcItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=50)),
                ('product_description', models.CharField(max_length=200)),
                ('has_catmat', models.BooleanField()),
                ('catmat', models.CharField(max_length=6)),
                ('ref_number', models.CharField(max_length=8)),
                ('unit', models.CharField(max_length=6)),
            ],
        ),
    ]
