# Generated by Django 3.0.3 on 2020-04-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgcitem',
            name='is_opened',
            field=models.BooleanField(default=False),
        ),
    ]
