# Generated by Django 3.0.3 on 2020-04-08 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pgc', '0002_pgcitem_is_opened'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PgcItem',
            new_name='PgcProduct',
        ),
    ]
