# Generated by Django 3.0.3 on 2020-04-08 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pgc', '0003_auto_20200408_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pgcproduct',
            old_name='is_opened',
            new_name='is_opened_to_order',
        ),
    ]
